[main]
summary=Balanced on battery for CachyOS (good runtime, still responsive)
include=powersave

[cpu]
governor=powersave
energy_performance_preference=balance_power
min_perf_pct=10
max_perf_pct=85
boost=1

[vm]
transparent_hugepages=madvise

[sysctl]
vm.swappiness=50
vm.vfs_cache_pressure=75
vm.dirty_background_bytes=67108864     # 64 MiB
vm.dirty_bytes=268435456               # 256 MiB

[audio]
timeout=10

[usb]
autosuspend=1

[script]
script=${i:PROFILE_DIR}/scripts/pci-pm.sh
