[main]
summary=Performance on battery for CachyOS (responsive bursts, turbo on)
include=balanced

[cpu]
governor=powersave
energy_performance_preference=balance_performance
min_perf_pct=20
max_perf_pct=95
boost=1

[vm]
transparent_hugepages=madvise

[sysctl]
vm.swappiness=30
vm.vfs_cache_pressure=50
vm.dirty_background_bytes=67108864     # 64 MiB
vm.dirty_bytes=268435456               # 256 MiB

[audio]
timeout=10

[usb]
autosuspend=1

[script]
script=${i:PROFILE_DIR}/scripts/pci-pm.sh
