[main]
summary=Max battery life for CachyOS (race to sleep, full efficiency)
include=powersave

[cpu]
governor=powersave
energy_performance_preference=power
min_perf_pct=10
max_perf_pct=70
boost=1

[vm]
transparent_hugepages=madvise

[sysctl]
vm.swappiness=60
vm.vfs_cache_pressure=100
vm.dirty_background_bytes=67108864     # 64 MiB
vm.dirty_bytes=268435456               # 256 MiB

[audio]
timeout=10

[usb]
autosuspend=1

[script]
script=${i:PROFILE_DIR}/scripts/pci-pm.sh
